apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgjobs
spec:
  selector:
    matchLabels:
      app: tgjobs
  template:
    metadata:
      labels:
        app: tgjobs
    spec:
      containers:
      - image: windingmonth/tgjobs
        name: tgjobs

---

apiVersion: v1
kind: Service
metadata:
  name: tgjobs
spec:
  type: ClusterIP
  ports:
    - name: "tgjobs"
      port: 80
  selector:
    app: tgjobs

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tgjobsingress
  labels:
    app: tgjobsingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "64"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/cors-allow-headers: >-
      DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: 'PUT, GET, POST, OPTIONS'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |-
        proxy_set_header X-Forwarded-For $remote_addr;
        access_log /var/log/nginx/demo.fantasysz.com.access.log upstreaminfo if=$loggable;
        error_log /var/log/nginx/demo.fantasysz.com.error.log;


spec:
  rules:
    - host: 'tgjobs.dev.fantasysz.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tgjobs
                port:
                  number: 80